Terraform/README.md
=> Fixed link to Terraform documentation

Ansible/collection/jfrog/ansible/roles/artifactory/templates/installer-info.json.j2, Ansible/collection/jfrog/ansible/roles/xray/templates/installer-info.json.j2
Changed the format of the call home/ installer_info template.
=> Changed the call home format.

AzureResourceManager/Xray/MP_submission/createUiDefinition.json, AzureResourceManager/Xray/MP_submission/mainTemplate.json, AzureResourceManager/Xray/MP_submission/scripts/install_xray.sh, AzureResourceManager/Xray/README.md, AzureResourceManager/Xray/azuredeploy_xray_vmss.json, AzureResourceManager/Xray/scripts/install_xray.sh, AzureResourceManager/Xray/vm_install/install_xray_to_vm.sh
Xray 3.8.5, no workaround needed anymore. Xray can connect to Azure Postgres service out of the box. Readme is modified
=> Azure xray 3.8.5

AzureResourceManager/Artifactory/MP_submission/createUiDefinition.json, AzureResourceManager/Artifactory/MP_submission/mainTemplate.json, AzureResourceManager/Artifactory/MP_submission/scripts/install_artifactory7.sh, AzureResourceManager/Artifactory/azuredeploy_ms_ps.json, AzureResourceManager/Artifactory/vm_install/install_pro7_to_vm.sh, AzureResourceManager/Artifactory/vm_install/vm_deploy.json, AzureResourceManager/Artifactory/vm_install/vm_parameters.json, AzureResourceManager/JCR/MP_submission_7/createUiDefinition.json, AzureResourceManager/JCR/MP_submission_7/mainTemplate.json, AzureResourceManager/JCR/MP_submission_7/scripts/install_artifactory7.sh, AzureResourceManager/JCR/azuredeploy.json, AzureResourceManager/JCR/scripts/install_artifactory7.sh, AzureResourceManager/JCR/vm_install/install_jcr7_to_vm.sh, AzureResourceManager/JCR/vm_install/vm_deploy.json, AzureResourceManager/JCR/vm_install/vm_parameters.json, AzureResourceManager/Xray/MP_submission/createUiDefinition.json, AzureResourceManager/Xray/MP_submission/mainTemplate.json, AzureResourceManager/Xray/MP_submission/scripts/install_xray.sh, AzureResourceManager/Xray/azuredeploy_xray.parameters.json, AzureResourceManager/Xray/azuredeploy_xray_vmss.json, AzureResourceManager/Xray/scripts/install_xray.sh, AzureResourceManager/Xray/vm_install/install_xray_to_vm.sh, AzureResourceManager/Xray/vm_install/vm_deploy.json, AzureResourceManager/Xray/vm_install/vm_parameters.json
- Added RT, JCR and Xray templates for the VM images creation
- RT and JCR versions updated to 7.10.2
- Xray version is updated to 3.9.1
- Version is passing to the script from the template parameters (reduce changes in the code on the version upgrades)
=> ARM templates for VM images

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, Ansible/README.md
* Current ansible collection only supports ubuntu flavours
* Centos/RHEL and SELinux support is coming soon, stay tuned :)
=> OS support and templates for PR/Issues

Ansible/CHANGELOG.md, Ansible/examples/host_vars/rt-ha/hosts.yml, Ansible/examples/host_vars/rt-xray-ha/hosts.yml, Ansible/examples/host_vars/rt-xray/hosts.yml, Ansible/examples/host_vars/ssl/hosts.yml, Ansible/examples/host_vars/xray/hosts.yml
- [ x] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
- [ x] CHANGELOG.md updated
- [x ] Variables and other changes are documented in the README.md
Updated example hosts file to be explicit about pulling password and keys from env vars so as not to accidentally use the example passwords, keys.
- Updated example hosts file to be explicit about pulling passwords,keys from env vars.
=> [ansible] Example hosts file to be explicit about pulling passwords,keys from env vars

README.md
Fixing parent readme to include link to Openshift4
=> [openshift] Updating parent readme to include link to openshift readme

Amazon/containers/buildAwsContainers.sh
=> updated build script as per new AWS Process and repo names

Amazon/Marketplace/v7153/templates/jfrog-artifactory-ec2-instance.template.yaml
=> Update AMI IDs after fix for S3 binary store template

AzureResourceManager/Artifactory/MP_submission/createUiDefinition.json, AzureResourceManager/Artifactory/MP_submission/mainTemplate.json, AzureResourceManager/Artifactory/azuredeploy.json, AzureResourceManager/Artifactory/vm_install/vm_parameters.json, AzureResourceManager/Xray/MP_submission/createUiDefinition.json, AzureResourceManager/Xray/MP_submission/mainTemplate.json, AzureResourceManager/Xray/azuredeploy_xray_vmss.json, AzureResourceManager/Xray/vm_install/vm_parameters.json
<!--
Thank you for contributing . 
Latest changes has committed for Artifactory version 7.17.5 & X-ray version 3.22.1 in all required files.
@danielmkn , Please verify and merge it.
=> Arm 7.17.5

AzureResourceManager/Artifactory/MP_submission/createUiDefinition.json, AzureResourceManager/Artifactory/MP_submission/mainTemplate.json, AzureResourceManager/Artifactory/azuredeploy.json, AzureResourceManager/Artifactory/vm_install/vm_parameters.json, AzureResourceManager/Xray/MP_submission/createUiDefinition.json, AzureResourceManager/Xray/MP_submission/mainTemplate.json, AzureResourceManager/Xray/azuredeploy_xray.parameters.json, AzureResourceManager/Xray/azuredeploy_xray_vmss.json, AzureResourceManager/Xray/vm_install/vm_parameters.json
All new changes for Artifactory version 7.18.6 & X-ray version 3.24.2 has committed in require configuration files.
@danielmkn , Please review and merge it.
=> Arm 7.18.6

AzureResourceManager/Artifactory/MP_submission/createUiDefinition.json, AzureResourceManager/Artifactory/MP_submission/mainTemplate.json, AzureResourceManager/Artifactory/azuredeploy.json, AzureResourceManager/Xray/MP_submission/createUiDefinition.json, AzureResourceManager/Xray/MP_submission/mainTemplate.json, AzureResourceManager/Xray/azuredeploy_xray.parameters.json, AzureResourceManager/Xray/azuredeploy_xray_vmss.json
Updated all changes in required template file for artifactory version 7.19.4 & X-ray version 3.25.1
@danielmkn , Please review the changes and merge it.
=> Arm 7.19.4

Amazon/cloudformation-modules/JFrog-Artifactory-EC2Instance-MODULE/.rpdk-config, Amazon/cloudformation-modules/JFrog-Artifactory-EC2Instance-MODULE/fragments/jfrog-artifactory-ec2-instance.template.yaml, Amazon/cloudformation-modules/JFrog-Artifactory-EC2Instance-MODULE/schema.json, Amazon/cloudformation-modules/JFrog-Xray-EC2Instance-MODULE/.rpdk-config, Amazon/cloudformation-modules/JFrog-Xray-EC2Instance-MODULE/fragments/jfrog-xray-ec2-instance.template.yaml, Amazon/cloudformation-modules/JFrog-Xray-EC2Instance-MODULE/schema.json, Amazon/cloudformation-modules/JFrog__Artifactory__Core__MODULE/.rpdk-config, Amazon/cloudformation-modules/JFrog__Artifactory__Core__MODULE/fragments/jfrog-artifactory-core-infrastructure.template.yaml, Amazon/cloudformation-modules/JFrog__Artifactory__Core__MODULE/schema.json, Amazon/cloudformation-modules/JFrog__Artifactory__ExistingVpc__MODULE/.rpdk-config, Amazon/cloudformation-modules/JFrog__Artifactory__ExistingVpc__MODULE/fragments/jfrog-artifactory-ec2-existing-vpc.template.yaml, Amazon/cloudformation-modules/JFrog__Artifactory__ExistingVpc__MODULE/schema.json, Amazon/cloudformation-modules/JFrog__Artifactory__NewVpc__MODULE/.rpdk-config, Amazon/cloudformation-modules/JFrog__Artifactory__NewVpc__MODULE/fragments/jfrog-artifactory-ec2-master.template.yaml, Amazon/cloudformation-modules/JFrog__Artifactory__NewVpc__MODULE/schema.json, Amazon/cloudformation-modules/aws-vpc-module/.rpdk-config, Amazon/cloudformation-modules/aws-vpc-module/fragments/aws-vpc.template.yaml, Amazon/cloudformation-modules/aws-vpc-module/schema.json, Amazon/cloudformation-modules/linux-bastion-module/.rpdk-config, Amazon/cloudformation-modules/linux-bastion-module/fragments/linux-bastion.template.yaml, Amazon/cloudformation-modules/linux-bastion-module/schema.json, Amazon/cloudformation-modules/test-cfts/.taskcat.yml, Amazon/cloudformation-modules/test-cfts/README.MD, Amazon/cloudformation-modules/test-cfts/create-vpc.yaml, Amazon/cloudformation-modules/test-cfts/existing-vpc.yaml, Amazon/cloudformation-modules/test-cfts/new-vpc.yaml, Amazon/cloudformation-modules/test-cfts/register.sh, Amazon/cloudformation-modules/test-cfts/service-2.json, Amazon/cloudformation-modules/test-cfts/submit.sh
=> modules first release

Amazon/cloudformation-modules/JFrog__Artifactory__ExistingVpc__MODULE/fragments/jfrog-artifactory-ec2-existing-vpc.template.yaml, Amazon/cloudformation-modules/JFrog__Artifactory__NewVpc__MODULE/fragments/jfrog-artifactory-ec2-master.template.yaml, Amazon/cloudformation-modules/test-cfts/README.MD, Amazon/cloudformation-modules/test-cfts/register.sh, Amazon/cloudformation-modules/test-cfts/submit.sh
=> upgraded modules to 7.21.5

AzureResourceManager/Artifactory/MP_submission/createUiDefinition.json, AzureResourceManager/Artifactory/MP_submission/mainTemplate.json, AzureResourceManager/Artifactory/azuredeploy.json, AzureResourceManager/Xray/MP_submission/createUiDefinition.json, AzureResourceManager/Xray/MP_submission/mainTemplate.json, AzureResourceManager/Xray/azuredeploy_xray.parameters.json, AzureResourceManager/Xray/azuredeploy_xray_vmss.json
All changes has committed for artifactory 7.21.3 & xray 3.7.2, Please review and merge it.
=> Arm 7.21.3

AzureResourceManager/Artifactory/MP_submission/createUiDefinition.json, AzureResourceManager/Artifactory/MP_submission/mainTemplate.json, AzureResourceManager/Artifactory/azuredeploy.json, AzureResourceManager/Xray/MP_submission/createUiDefinition.json, AzureResourceManager/Xray/MP_submission/mainTemplate.json, AzureResourceManager/Xray/azuredeploy_xray.parameters.json, AzureResourceManager/Xray/azuredeploy_xray_vmss.json
All changes has committed in templates file for artifactory 7.21.8 & xray 3.27.4 version.
Please verify and merge it.
=> Arm 7.21.8

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/missioncontrol/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/missioncontrol/files/searchguard/sg_config.yml, Ansible/ansible_collections/jfrog/platform/roles/missioncontrol/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/missioncontrol/tasks/main.yml, Ansible/ansible_collections/jfrog/platform/roles/missioncontrol/tasks/setup-elasticsearch.yml, Ansible/ansible_collections/jfrog/platform/roles/missioncontrol/tasks/setup-searchguard.yml, Ansible/ansible_collections/jfrog/platform/roles/missioncontrol/tasks/upgrade-elasticsearch.yml, Ansible/ansible_collections/jfrog/platform/roles/missioncontrol/tasks/upgrade-searchguard.yml, Ansible/ansible_collections/jfrog/platform/roles/missioncontrol/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/missioncontrol/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/missioncontrol/vars/script/archive.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/tasks/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #132 
=> [Ansible] JFrog Platform 7.23.3

AzureResourceManager/Artifactory/MP_submission/createUiDefinition.json, AzureResourceManager/Artifactory/MP_submission/mainTemplate.json, AzureResourceManager/Artifactory/azuredeploy.json, AzureResourceManager/Xray/MP_submission/createUiDefinition.json, AzureResourceManager/Xray/MP_submission/mainTemplate.json, AzureResourceManager/Xray/azuredeploy_xray.parameters.json, AzureResourceManager/Xray/azuredeploy_xray_vmss.json
All changes has committed for artifactory 7.25.6 & xray 3.32.2 in required template files.
Please review & merge it
=> Arm 7.25.6

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [Ansible][jfrog-platform] 10.0.3 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml
=> JFrog Platform 10.0.4 release

Amazon/marketplace-jfrog-artifactory/v72710/templates/jfrog-artifactory-core-infrastructure.template.yaml, Amazon/marketplace-jfrog-artifactory/v72710/templates/jfrog-artifactory-ec2-existing-vpc.template.yaml, Amazon/marketplace-jfrog-artifactory/v72710/templates/jfrog-artifactory-ec2-instance.template.yaml, Amazon/marketplace-jfrog-artifactory/v72710/templates/jfrog-xray-ec2-instance.template.yaml
=> AWS MP 7.27.10

AzureResourceManager/Artifactory/MP_submission/createUiDefinition.json, AzureResourceManager/Artifactory/MP_submission/mainTemplate.json, AzureResourceManager/Artifactory/azuredeploy.json, AzureResourceManager/Xray/MP_submission/createUiDefinition.json, AzureResourceManager/Xray/MP_submission/mainTemplate.json, AzureResourceManager/Xray/azuredeploy_xray.parameters.json, AzureResourceManager/Xray/azuredeploy_xray_vmss.json
Committed all changes for artifactory 7.27.9 & xray 3.35.0 . Please review and merge it.
=> Arm 7.27.9

AzureResourceManager/Artifactory/README.md, AzureResourceManager/Xray/README.md
=> GH-182, fixing the deployment button

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/tasks/Debian.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/tasks/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/tasks/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/tasks/Debian.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/tasks/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/tasks/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/tasks/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/tasks/main.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/templates/postgresql.conf.j2, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.1.0 release

AzureResourceManager/Artifactory/MP_submission/createUiDefinition.json, AzureResourceManager/Artifactory/MP_submission/mainTemplate.json, AzureResourceManager/Artifactory/azuredeploy.json, AzureResourceManager/Xray/MP_submission/createUiDefinition.json, AzureResourceManager/Xray/MP_submission/mainTemplate.json, AzureResourceManager/Xray/azuredeploy_xray.parameters.json, AzureResourceManager/Xray/azuredeploy_xray_vmss.json
All changes has committed for artifactory 7.27.10 & xray 3.37.2 . Please review and merge it.
=> Arm 7.27.10

Amazon/cloudformation-modules/JFrog__Artifactory__ExistingVpc__MODULE/fragments/jfrog-artifactory-ec2-existing-vpc.template.yaml, Amazon/cloudformation-modules/JFrog__Artifactory__NewVpc__MODULE/fragments/jfrog-artifactory-ec2-master.template.yaml, Amazon/cloudformation-modules/test-cfts/submit.sh
=> Updated RT and Xray version and republished modules

AzureResourceManager/Artifactory/MP_submission/createUiDefinition.json, AzureResourceManager/Artifactory/MP_submission/mainTemplate.json, AzureResourceManager/Artifactory/azuredeploy.json
All changes has committed for artifactory 7.29.7 . Please review and merge it.
=> Arm 7.29.7

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.1.2 release

AzureResourceManager/Artifactory/MP_submission/createUiDefinition.json, AzureResourceManager/Artifactory/MP_submission/mainTemplate.json, AzureResourceManager/Artifactory/azuredeploy.json, AzureResourceManager/Xray/MP_submission/createUiDefinition.json, AzureResourceManager/Xray/MP_submission/mainTemplate.json, AzureResourceManager/Xray/azuredeploy_xray.parameters.json, AzureResourceManager/Xray/azuredeploy_xray_vmss.json
All changes has commited for Artifactory 7.29.8 and Xray 3.38.2 . Please review and merge it.
=> Arm 7.29.8

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.2.0 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/shared/ensure_permissions_correct.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.3.0 release

Openshift4/helm/openshift-artifactory-ha/CHANGELOG.md, Openshift4/helm/openshift-artifactory-ha/Chart.lock, Openshift4/helm/openshift-artifactory-ha/Chart.yaml, Openshift4/helm/openshift-artifactory-ha/values.yaml, Openshift4/helm/openshift-xray/CHANGELOG.md, Openshift4/helm/openshift-xray/Chart.lock, Openshift4/helm/openshift-xray/Chart.yaml, Openshift4/helm/openshift-xray/values.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/CHANGELOG.md, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.lock, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/values.yaml, Openshift4/operator/xray-operator/helm-charts/openshift-xray/CHANGELOG.md, Openshift4/operator/xray-operator/helm-charts/openshift-xray/Chart.lock, Openshift4/operator/xray-operator/helm-charts/openshift-xray/Chart.yaml, Openshift4/operator/xray-operator/helm-charts/openshift-xray/values.yaml
=> PTRENG-3208 [Openshift] Artifactory 7.27.9 & Xray 3.35.0

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.3.2 release

Openshift4/operator/artifactory-ha-operator/CHANGELOG.md, Openshift4/operator/artifactory-ha-operator/Dockerfile, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/CHANGELOG.md, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.lock, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/values.yaml, Openshift4/operator/artifactory-ha-operator/watches.yaml, Openshift4/operator/xray-operator/CHANGELOG.md, Openshift4/operator/xray-operator/Dockerfile, Openshift4/operator/xray-operator/helm-charts/openshift-xray/CHANGELOG.md, Openshift4/operator/xray-operator/helm-charts/openshift-xray/Chart.lock, Openshift4/operator/xray-operator/helm-charts/openshift-xray/Chart.yaml, Openshift4/operator/xray-operator/helm-charts/openshift-xray/values.yaml, Openshift4/operator/xray-operator/watches.yaml
=> [Openshift] Artifactory 7.33.12 & Xray 3.43.1

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/README.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
- [] Variables and other changes are documented in the README.md
=> [ansible] JFrog Platform 10.4.0 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.4.1 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.5.0 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.5.1 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.5.2 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/shared/selinux_configure_context.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/shared/selinux_restore_context.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.6.0 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.6.1 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/tasks/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/templates/nginx.conf.j2, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/README.md, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/tasks/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/templates/nginx.conf.j2, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.6.2 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.7.0 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.8.0 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.8.1 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.8.2 release

AzureResourceManager/Artifactory/MP_submission/createUiDefinition.json, AzureResourceManager/Artifactory/MP_submission/mainTemplate.json, AzureResourceManager/Artifactory/MP_submission/nested/MSSQL_deploy.json, AzureResourceManager/Artifactory/nested/MSSQL_deploy.json, AzureResourceManager/Xray/MP_submission/createUiDefinition.json, AzureResourceManager/Xray/MP_submission/mainTemplate.json
=> Changes in RT and Xray version 7.41.7 and 3.55.2

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [anisble] JFrog Platform 10.8.4 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [anisble] JFrog Platform 10.8.5 release

Openshift4/helm/openshift-artifactory-ha/CHANGELOG.md, Openshift4/helm/openshift-artifactory-ha/Chart.lock, Openshift4/helm/openshift-artifactory-ha/Chart.yaml, Openshift4/helm/openshift-artifactory-ha/values.yaml, Openshift4/helm/openshift-xray/CHANGELOG.md, Openshift4/helm/openshift-xray/Chart.lock, Openshift4/helm/openshift-xray/Chart.yaml, Openshift4/helm/openshift-xray/README.md, Openshift4/helm/openshift-xray/values.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/CHANGELOG.md, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.lock, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/values.yaml, Openshift4/operator/xray-operator/helm-charts/openshift-xray/CHANGELOG.md, Openshift4/operator/xray-operator/helm-charts/openshift-xray/Chart.lock, Openshift4/operator/xray-operator/helm-charts/openshift-xray/Chart.yaml, Openshift4/operator/xray-operator/helm-charts/openshift-xray/README.md, Openshift4/operator/xray-operator/helm-charts/openshift-xray/values.yaml
=> Changes in RT and Xray version 7.41.13 and 3.57.6

Openshift4/operator/artifactory-ha-operator/Dockerfile, Openshift4/operator/xray-operator/Dockerfile
=> Changes in operator versions on Dockerfile

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [anisble] JFrog Platform 10.8.6 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/README.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/handlers/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/meta/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/shared/install_service.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/distro/Amazon.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/README.md, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/meta/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/tasks/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/templates/artifactory.conf.j2, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/README.md, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/meta/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/tasks/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/tasks/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/templates/artifactory.conf.j2, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.9.0 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.9.1 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.9.3 release

AzureResourceManager/Artifactory/MP_submission/createUiDefinition.json, AzureResourceManager/Artifactory/MP_submission/mainTemplate.json, AzureResourceManager/Artifactory/azuredeploy.json, AzureResourceManager/Xray/MP_submission/createUiDefinition.json, AzureResourceManager/Xray/MP_submission/mainTemplate.json, AzureResourceManager/Xray/azuredeploy_xray_vmss.json
=> Bump Artifactory and Xray versions

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/README.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/meta/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.10.0 release

Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/upgrade.yml
Zachary.Wayer@garmin.com
- [ X] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
Improve play to better handle nodes without internet access. By pinning tasks to occur when the tar is downloaded or unarchived it allows for more coverage of scenarios.
Similarly, check to see if the jdbc driver provided as part of the tar is the version set in the variables.
This allows for users to provide the tar in presteps to calling the role if they choose / need to.
**Special notes for …
=> Ansible/Artifactory - Improve offline upgrades

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.11.5 release

Openshift4/helm/openshift-artifactory-ha/CHANGELOG.md, Openshift4/helm/openshift-artifactory-ha/Chart.lock, Openshift4/helm/openshift-artifactory-ha/Chart.yaml, Openshift4/helm/openshift-artifactory-ha/values.yaml, Openshift4/helm/openshift-xray/CHANGELOG.md, Openshift4/helm/openshift-xray/Chart.lock, Openshift4/helm/openshift-xray/Chart.yaml, Openshift4/helm/openshift-xray/rabbitmq.yaml, Openshift4/helm/openshift-xray/values.yaml, Openshift4/operator/artifactory-ha-operator/CHANGELOG.md, Openshift4/operator/artifactory-ha-operator/Dockerfile, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/CHANGELOG.md, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.lock, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/values.yaml, Openshift4/operator/xray-operator/CHANGELOG.md, Openshift4/operator/xray-operator/Dockerfile, Openshift4/operator/xray-operator/helm-charts/openshift-xray/CHANGELOG.md, Openshift4/operator/xray-operator/helm-charts/openshift-xray/Chart.lock, Openshift4/operator/xray-operator/helm-charts/openshift-xray/Chart.yaml, Openshift4/operator/xray-operator/helm-charts/openshift-xray/rabbitmq.yaml, Openshift4/operator/xray-operator/helm-charts/openshift-xray/values.yaml
=> Changes in RT version 7.49.8 and Xray version 3.67.9

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/tasks/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/tasks/RedHat.yml
When SELinux is enabled on RedHat systems Nginx needs extra permission to open a socket to proxy for Artifactory.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #268 
Testing should be done on a RHEL/Alma/Rocky/Oracle Linux.
=> [ansible/artifactory] nginx needs SELinux boolean.

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/tasks/main.yml
The private key of a TLS certificate is protected.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #266 
One-liner.
=> [ansible/artifactory] Fix file permission of Nginx TLS key

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/ansible.cfg, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/rabbitmq/setup/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/rabbitmq/upgrade/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.12.2 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/roles/postgres/handlers/main.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/templates/override.conf.j2
Bugfix. Setting a custom PGDATA directory crashed postgres.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #223
More info in the issue #223
=> [ansible/artifactory] Fix for #223 Changing PGDATA

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/README.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/meta/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/meta/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/meta/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/tasks/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/meta/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/meta/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/meta/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/meta/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.13.0 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/README.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #296 
=> [ansible] JFrog Platform 10.13.1 release

Ansible/ansible_collections/jfrog/platform/roles/postgres/tasks/Debian.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/tasks/RedHat.yml
Retry downloads from postgresql.org 3 times to workaround network glitches.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #293
=> [ansible/artifactory] Retry handlers, fix for #293

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/README.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/templates/binarystore.xml.j2, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #305 
=> [ansible] JFrog Platform 10.13.3 release

Openshift4/helm/openshift-artifactory-ha/CHANGELOG.md, Openshift4/helm/openshift-artifactory-ha/Chart.lock, Openshift4/helm/openshift-artifactory-ha/Chart.yaml, Openshift4/helm/openshift-artifactory-ha/values.yaml, Openshift4/helm/openshift-xray/CHANGELOG.md, Openshift4/helm/openshift-xray/Chart.lock, Openshift4/helm/openshift-xray/Chart.yaml, Openshift4/helm/openshift-xray/rabbitmq.yaml, Openshift4/helm/openshift-xray/values.yaml, Openshift4/operator/artifactory-ha-operator/CHANGELOG.md, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/CHANGELOG.md, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.lock, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/values.yaml, Openshift4/operator/xray-operator/CHANGELOG.md, Openshift4/operator/xray-operator/helm-charts/openshift-xray/CHANGELOG.md, Openshift4/operator/xray-operator/helm-charts/openshift-xray/Chart.lock, Openshift4/operator/xray-operator/helm-charts/openshift-xray/Chart.yaml, Openshift4/operator/xray-operator/helm-charts/openshift-xray/rabbitmq.yaml, Openshift4/operator/xray-operator/helm-charts/openshift-xray/values.yaml
=> Updated versions of RT 7.59.11 and Xray 3.76.7

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/README.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/templates/binarystore.xml.j2
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #313 
=> [jfrog-platform] 10.14.1 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/README.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #315 
=> [ansible] JFrog Platform 10.14.3 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.14.5 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.14.6 release

Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml
This PR increases the maximum amount of memory for Artifactory to 4G as suggested.
Support case 263585
GitHub issue #328 
=> [ansible/artifactory] Increase heap space in artifactory java opts

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #329 
=> [ansible] JFrog Platform 10.15.0 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/artifactory.yml, Ansible/ansible_collections/jfrog/platform/distribution.yml, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/insight.yml, Ansible/ansible_collections/jfrog/platform/postgres.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml, Ansible/ansible_collections/jfrog/platform/xray.yml
=> [ansible] JFrog Platform 10.15.3 release

Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml
This fixes the src filename of the bootstrap.creds that set the admin password for artifactory.
Please merge ASAP
=> [ansible/artifactory] Hotfix for issue #294 in latest release

Openshift4/helm/openshift-artifactory-ha/CHANGELOG.md, Openshift4/helm/openshift-artifactory-ha/Chart.lock, Openshift4/helm/openshift-artifactory-ha/Chart.yaml, Openshift4/helm/openshift-artifactory-ha/values.yaml, Openshift4/helm/openshift-xray/CHANGELOG.md, Openshift4/helm/openshift-xray/Chart.lock, Openshift4/helm/openshift-xray/Chart.yaml, Openshift4/helm/openshift-xray/values.yaml, Openshift4/operator/artifactory-ha-operator/CHANGELOG.md, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/CHANGELOG.md, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.lock, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/values.yaml, Openshift4/operator/xray-operator/CHANGELOG.md, Openshift4/operator/xray-operator/helm-charts/openshift-xray/CHANGELOG.md, Openshift4/operator/xray-operator/helm-charts/openshift-xray/Chart.lock, Openshift4/operator/xray-operator/helm-charts/openshift-xray/Chart.yaml, Openshift4/operator/xray-operator/helm-charts/openshift-xray/values.yaml
=> openshift rt-7.71.5 and xray-3.85.5

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/README.md, Ansible/ansible_collections/jfrog/platform/roles/postgres/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/tasks/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #361 
=>  JFrog Platform 10.16.5 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/README.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.17.0 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/README.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.17.1 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.17.3 release

Openshift4/RedHatImages/Dockerfile.redhat-ubi-rt-initcontainer, Openshift4/RedHatImages/Dockerfile.redhat-ubi-rt7, Openshift4/helm/openshift-artifactory-ha/CHANGELOG.md, Openshift4/helm/openshift-artifactory-ha/Chart.lock, Openshift4/helm/openshift-artifactory-ha/Chart.yaml, Openshift4/helm/openshift-artifactory-ha/values.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/CHANGELOG.md, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.lock, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/values.yaml
=> bump up artifactory version to 7.77.7

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.17.4 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.18.1 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.18.2 release

Openshift4/helm/openshift-artifactory-ha/CHANGELOG.md, Openshift4/helm/openshift-artifactory-ha/Chart.lock, Openshift4/helm/openshift-artifactory-ha/Chart.yaml, Openshift4/helm/openshift-artifactory-ha/values.yaml, Openshift4/operator/artifactory-ha-operator/Dockerfile, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/CHANGELOG.md, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.lock, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/values.yaml
=> Bump up Artitfactory version for openshift operator 1.3.0

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.19.0 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.19.1 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.19.3 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.20.0 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.20.2 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.20.3 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/tasks/expect.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/script/archive.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/handlers/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/expect.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/script/archive.yml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #424 , #436 
=> [ansible] JFrog Platform 11.0.1 release

Openshift4/RedHatImages/Dockerfile.redhat-ubi-rt-initcontainer, Openshift4/RedHatImages/Dockerfile.redhat-ubi-rt7, Openshift4/helm/openshift-artifactory-ha/CHANGELOG.md, Openshift4/helm/openshift-artifactory-ha/Chart.lock, Openshift4/helm/openshift-artifactory-ha/Chart.yaml, Openshift4/helm/openshift-artifactory-ha/values.yaml, Openshift4/operator/artifactory-ha-operator/Dockerfile, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/CHANGELOG.md, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.lock, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/values.yaml
[Openshift] Releasing 7.104.10 version
=> [Openshift] Releasing 7.104.10 version

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 11.0.3 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 11.0.5 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 11.0.6 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 11.1.1 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 11.1.2 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 11.1.4 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/README.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 11.1.8 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 11.1.9 release

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/vars/Debian.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 11.2.1 release
