jfrog/JFrog-Cloud-Installers

Terraform/userdata.sh
NGINX access logs looked like ` -  [] ""   "" "" ""` before escaping this since nginx needs the literal "$values" but bash was interpreting them.
=> Terraform log_format not escaped

AzureResourceManager/MP_submission_7/createUiDefinition.json, AzureResourceManager/azuredeploy.json, JFrogContainerRegistry/AzureResourceManager/MP_submission_7/createUiDefinition.json, JFrogContainerRegistry/AzureResourceManager/MP_submission_7/mainTemplate.json, JFrogContainerRegistry/AzureResourceManager/azuredeploy.json
Standard_A2_v2 is removed from both HA and JCR templates.
=> Arm template fix vms

AzureResourceManager/Artifactory/MP_submission/nested/Postgresql_deploy.json, AzureResourceManager/Artifactory/MP_submission/scripts/install_artifactory7.sh, AzureResourceManager/Artifactory/nested/Postgresql_deploy.json, AzureResourceManager/Artifactory/scripts/install_artifactory7.sh, AzureResourceManager/Artifactory/vm_install/install_pro7_to_vm.sh, AzureResourceManager/JCR/MP_submission_7/scripts/install_artifactory7.sh, AzureResourceManager/JCR/scripts/install_artifactory7.sh, AzureResourceManager/Postgresql/azurePostgresDBDeploy.json
- Fixed bug in the Nginx config (not escaped $ characters)
- Postgresql storage increased for Xray and Artifactory, as well as in standalone Postgresql template. Default 5 Gb is not enough for both.  
- Different callhome data is used by the plain VM image and if this image is used in the ARM template (PTRENG-1226)
=> ARM template bug fixes and improvements

Amazon/Marketplace/v7153/templates/jfrog-artifactory-core-infrastructure.template.yaml, Amazon/Marketplace/v7153/templates/jfrog-artifactory-ec2-existing-vpc.template.yaml, Amazon/Marketplace/v7153/templates/jfrog-artifactory-ec2-instance.template.yaml, Amazon/Marketplace/v7153/templates/jfrog-xray-ec2-instance.template.yaml
- Remove unused QsS3* parameters
- Replace DatabaseEngine param with hardcoded values
- Remove bastion resources
- Replace RT and Xray version params with hardcoded values
- Remove all unnecessary steps in user scripts
- Update AMI IDs
- Other tidying up
=> Updates for AWS CFT for 7.15.3

.github/workflows/cla.yml
Update the CLA assistant to accept whitespace between "I have read the CLA Document and I hereby sign the CLA" comment. Same as https://github.com/jfrog/jfrog-cli/blob/master/.github/workflows/cla.yml
=> Update cla assistant

Ansible/ansible_collections/jfrog/platform/roles/artifactory/handlers/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/shared/install_service.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/upgrade.yml
We faced the issue following Issue (https://www.jfrog.com/jira/browse/RTFACT-27237) on our Artifactory Installation which is maintained through Ansible. After Nir published the Article on this (https://jfrog.com/knowledge-base/artifactory-why-does-my-linux-archive-service-installation-fail-degrade-after-an-upgrade/) I was wondering why Ansible would not Call `installService.sh` as part of the upgrade Process.
[RTFACT-27237 on JIRA](https://www.jfrog.com/jira/browse/RTFACT-27237)
=> [ansible/artifactory] Added "installService.sh" after upgrading Artifactory

Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/upgrade.yml
When running the upgrade play the stop artifactory is never notified. So running flush_handlers never actually gets hit.
Add notify to unarchive task, with the idea being if you're unarchiving a new version this means that host will be taking an update.
zachary.wayer@garmin.com
- [ x] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
When running the upgrade play the stop artifactory is never notified. So running flush_handlers never actually gets hit.
Add notify to unarchive task, with the idea being if you're unarchiving a new version this means that host will be taking an update.
**Which issue this PR fixes** *(optional, in …
=> [Ansible/Artifactory] -Upgrade play to stop artifactory service 

Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/tasks/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/tasks/RedHat.yml
**What this PR does / why we need it**:  Corporate firewalls are now limiting access to HTTP URLs. The Debian tasks already point to HTTPS URLs for the Nginx installer, RedHat should also point towards HTTPS, in my opinion. 
**Special notes for your reviewer**: This will help us complete a POC we have with JFrog.
=> [ansible] Update RedHat Nginx installer tasks to use HTTPS URLs

Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx/tasks/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/tasks/main.yml
Allow overriding the templates for nginx configs for `artifactory_nginx` and  `artifactory_nginx_ssl` roles.
This would allow configuring features like proxy timeouts, log formats, real ip module configs which are needed in production environments. 
Apart from that, currently TLS certificate and key are printed to ansible logs, which is a big security concern.
=> [ansible/artifactory] Allow overriding nginx config templates

Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/handlers/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml
In my use case I build an AMI image of artifactory host. 
The role starts Artifactory service unconditionally,  which is harmful in my case, because
Artifactory process connects to existing database and may perform an unwanted database migration.
This PR adds a variable `artifactory_start_service` that defaults to true.
When set to false, it prevents handlers from starting Artifactory and skips the health check at the end.
=> [ansible/artifactory] Conditionally start Artifactory service

Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/handlers/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/upgrade.yml
In my use case I build an AMI image of Xray host. 
The role starts Xray service unconditionally,  which is harmful in my case, because
Xray process connects to existing database and may perform an unwanted database migration.
This PR adds a variable `xray_start_service` that defaults to `true`.
When set to false, it prevents handlers from starting Xray and skips the health check at the end.
=> [ansible/xray] Conditionally start Xray service

Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/upgrade.yml
Artifactory and Xray rely on crontab to facilitate log rotation.
Current ansible roles do not configure access to crontab for users `artifactory` or `xray`. 
This results in the following errors:
```
xrayManage.sh[43290]: /etc/cron.allow: Permission denied
```
and
```
The user artifactory cannot use this program (crontab)
The user xray cannot use this program (crontab)
```
I haven't checked other products for this problem, please let me know if the fix needs to be added to other roles.
=> [ansible/artifactory, ansible/xray] Allow using crontab

Ansible/ansible_collections/jfrog/platform/roles/artifactory/handlers/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/upgrade.yml
Title of the PR starts with installer/product name (e.g. [ansible/artifactory])
CHANGELOG.md updated
Variables and other changes are documented in the README.md
What this PR does / why we need it:
Found a recent MR in the master branch that wasn't working as expected. The addition of the 'artifactory_start_serviceseemed to be not working as expected when trying to use it to build an AWS AMI image, where the service should not start.  Instead, the Ansible portion was failing because the playbook/role was still trying to start the Artifactory image when artifactory_start_service was defined as 'false'.  Adding the| bool` to the playbook allowed it to skip the startup and subsequent restart of the …
=> [ansible/artifactory] Fix for #284 - Updating flag handler to be boolean

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/README.md, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/tasks/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/templates/artifactory.conf.j2
The current role `artifactory_ginx_ssl` requires passing in variables containing:
the TLS certificate value for the instance
the certificate key value
This is fine if you have a self-signed (or externally signed) certificate purchased specifically for your Artifactory instance, but it doesn't work with e.g. LetsEncrypt or ZeroSSL certificates which are being renewed every 3 months asynchronously. This PR introduces variables to be able to use an external process. The default value, `ssl_certificate_install: true`, continues to install the SSL certificate and private key. Setting this to `false` avoids the race-conditions on these files.
**Which issue this PR …
=> [ansible/artifactory] Fix for #195 Allow external TLS certs

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/roles/artifactory/shared/selinux_restore_context.yml
Fixes an SELinux issue on AlmaLinux 8 (and probably Rocky/Oracle/Fedora)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #281
Check /var/log/messages on AlmaLinux8
=> [ansible/artifactory] Fix for #281 restore SELinux context on bin directory on RedHat-like distros

Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/files/redirect_http_to_https.conf
Without this fix a http request gets the default Nginx page instead of the Artifactory UI.
Configuration no follows Mozilla SSL Configurator.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #298
See also the Mozilla TLS configuration tool: [https://ssl-config.mozilla.org](https://ssl-config.mozilla.org/#server=nginx&version=1.24.0&config=intermediate&openssl=1.1.1k&ocsp=false&guideline=5.7)
=> [ansible/artifactory] Fix for #298 redirect http to https

Ansible/ansible_collections/jfrog/platform/roles/artifactory/shared/install_service.yml
This MR makes the "Create artifactory service" task notify the "Restart artifactory" handler. Since the "Create artifactory service" task stops the artifactory service if it is running, this change ensures the service gets up and running again.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #307 
In addition to this change, skipping the "Create artifactory service" task would be great if the service is already installed; however, I'm unsure how to check for that.
=> [ansible/artifactory] Fix for #307 artifactory service stopping

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/roles/artifactory/shared/install_service.yml
Partial revert of [GH-307](https://github.com/jfrog/JFrog-Cloud-Installers/issues/307), the service files must be updated every time the application is updated per [this](https://jfrog.com/help/r/artifactory-why-does-my-linux-archive-service-installation-fail-degrade-after-an-upgrade/description) jfrog article. Without this, the java options are not set properly. This change should still restart the artifactory service since it has the `notify` for the handler.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #320
=> [ansible/artifactory] - Fix service update

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/files/redirect_http_to_https.conf
Double slashes in the URL need to be corrected.
According to https://ssl-config.mozilla.org/#server=nginx&version=1.24.0&config=intermediate&openssl=1.1.1k&ocsp=false&guideline=5.7 mentioned in #298, one should use `return 301 https://$host$request_uri;`. However, what was added to the PR associated with #298 was `return 301 https://$host/$request_uri;` with a slash after $host, causing this issue.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #324 
=> [ansible/artifactory] Fixes #324 double slash when redirecting from http to https

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/README.md, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/templates/bootstrap.creds.j2
This PR creates the initial admin password with the chosen string. It suggests using ansible-vault to encrypt it.
We need it because software deployed with default passwords is a bad practice.
#294 
Credits to @eugene-krivosheyev for the initial solution.
=> [ansible/artifactory] Configure admin credentials 

Ansible/ansible_collections/jfrog/platform/roles/postgres/tasks/install.yml
The looping in the creation tasks for user, database and privileges in the postgres role did not fail on undefined values. Input validation was missing, and the logging of item=None is not so useful.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
fixes #311 
=> [ansible/artifactory] Assert that database username and password are defined.

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/templates/bootstrap.creds.j2
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #342 
=> [ansible] JFrog Platform 10.16.1 release

Ansible/ansible_collections/jfrog/platform/README.md
Sometimes Artifactory launches, but port 8082 or 8081 is not listening on IPv4.
This addistion to the README.md explains how to deal with IPv6 binding issue.
**Which issue this PR fixes** 
fixes #347
=> [ansible/artifactory] IPv6 in README.md

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/roles/postgres/README.md, Ansible/ansible_collections/jfrog/platform/roles/postgres/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/tasks/RedHat.yml
Fixes the URL of the Postgresql RPM GPG key to the new location, using a default variable. 
Install with included postgres role is broken since yesterday.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #361 
=> [ansible/artifactory] Fix for #361 postgres_rpmkey_url

Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/upgrade.yml
Changes the way that the Artifactory product version is obtained.
**Which issue this PR fixes**: fixes #365
`ansible.builtin.slurp` could also be used if we want to not rely on a temporary file, but it requires some filtering within Ansible to the same data.
=> [ansible/artifactory] Use `fetch` and `lookup('ini')` to get the version

Ansible/ansible_collections/jfrog/platform/roles/postgres/tasks/install.yml
Currently, the Postgres username and password are being displayed in plain text as part of the assertion task. Thus, rendering the no_log in [these](https://github.com/jfrog/JFrog-Cloud-Installers/blob/master/Ansible/ansible_collections/jfrog/platform/roles/postgres/tasks/install.yml#L94-L136) subsequent tasks useless. 
=> [ansible/artifactory] Added `no_log` to postgres username password assertion

Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/rabbitmq/setup/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/rabbitmq/upgrade/RedHat.yml
This adds support for EL9 distros (e.g. RHEL 9 and CentOS 9). Without this fix, Xray installation fails on EL 9 distributions because it attempts to install incompatible RPM packages for _socat_ and _erlang_.
=> [ansible/artifactory] Support RHEL 9 in rabbitmq setup

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/README.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/rabbitmq/setup/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/rabbitmq/upgrade/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
=> [ansible] JFrog Platform 10.18.0 release 

Openshift4/README.md
=> [openshift] JFrog highly recommends using JFrog Helm Charts for deployments on OpenShift clusters

Openshift4/helm/openshift-artifactory-ha/CHANGELOG.md, Openshift4/helm/openshift-artifactory-ha/Chart.lock, Openshift4/helm/openshift-artifactory-ha/Chart.yaml, Openshift4/helm/openshift-artifactory-ha/values.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/CHANGELOG.md, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.lock, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/values.yaml
=> [Openshift] Releasing 7.90.8 version

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
- [ x] Variables and other changes are documented in the README.md
=> [ansible] JFrog Platform 10.19.7 release

Openshift4/helm/openshift-artifactory-ha/CHANGELOG.md, Openshift4/helm/openshift-artifactory-ha/Chart.lock, Openshift4/helm/openshift-artifactory-ha/Chart.yaml, Openshift4/helm/openshift-artifactory-ha/values.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/CHANGELOG.md, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.lock, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/Chart.yaml, Openshift4/operator/artifactory-ha-operator/helm-charts/openshift-artifactory-ha/values.yaml
=> [Openshift] Releasing 7.98.7 version

Ansible/ansible_collections/jfrog/platform/roles/postgres/templates/pg_hba.conf.j2
This PR allows controlling the auth method for remote database clients. If `postgres_listen_addresses` variable is not change, the installed postgres will listen on all interfaces. This allows a more secure setup of the auth method, from 'trust' to 'password' for instance.
Support case 326048
SECURITY PATCH
=> [ansible/postgres] Fix for auth method in pg_hba.conf file 

Ansible/ansible_collections/jfrog/platform/CHANGELOG.md, Ansible/ansible_collections/jfrog/platform/galaxy.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/shared/access_configuration.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory/templates/access-config-patch.yml.j2, Ansible/ansible_collections/jfrog/platform/roles/artifactory/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/README.md, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/tasks/main.yml, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/templates/artifactory.conf.j2, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/templates/certificate.cakey.j2, Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/templates/certificate.crt.j2, Ansible/ansible_collections/jfrog/platform/roles/distribution/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/distribution/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/insight/vars/main.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/tasks/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/postgres/templates/pg_hba.conf.j2, Ansible/ansible_collections/jfrog/platform/roles/xray/defaults/main.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/expect.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/install.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/rabbitmq/setup/RedHat.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/upgrade.yml, Ansible/ansible_collections/jfrog/platform/roles/xray/vars/main.yml
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #422  , #413 , #417 , #418 , #380 , #419 , #411
=> [ansible] JFrog Platform 10.20.1 release

Ansible/ansible_collections/jfrog/platform/roles/artifactory_nginx_ssl/templates/artifactory.conf.j2
Amends `server_name` to create a `repo` variable in Nginx config. That is needed for the rewrite rule when artifactory_docker_registry_subdomain is true.
```  
{% if artifactory_docker_registry_subdomain %}rewrite ^/(v1|v2)/(.*) /artifactory/api/docker/$repo/$1/$2;{% endif %}
```
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #353
=> [ansible/artifactory] Bugfix when enabling artifactory_docker_registry_subdomain 
